name: 'Greeting'
description: 'Greet someone'
inputs:
  first_name:
    description: 'Who to greet'
    required: true
  last_name:
    description: 'Who to greet'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    first_name: ${{ inputs.first_name }}
    last_name: ${{ inputs.last_name }}